name: Deploy Azure Function App

on:
  push:
    branches:
      - master  # Deploys when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust based on your function runtime

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURECREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: "myaiafz01"  # Change this to your Azure Function App name
          package: "./backend"
