name: Deploy Azure Function App

on:
  push:
    branches:
      - master  # Deploys when code is pushed to main branch

env:
  AZURE_FUNCTIONAPP_NAME: 'myaiazf02'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/BlobTrigger2'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}  # Adjust based on your function runtime

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURECREDENTIALS }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
